<?php

namespace App\Filament\Resources;

use App\Filament\Resources\ExamPaperMarkingKeyResource\Pages;
use App\Filament\Resources\ExamPaperMarkingKeyResource\RelationManagers;
use App\Models\ExamPaper;
use App\Models\ExamPaperMarkingKey;
use App\Models\ExamTotalQuestion;
use App\Models\Program;
use App\Models\User;
use Carbon\Carbon;
use Filament\Tables\Actions\ActionGroup;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Notifications\Notification;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class ExamPaperMarkingKeyResource extends Resource
{
    protected static ?string $model = ExamPaperMarkingKey::class;

    protected static ?string $navigationIcon = 'heroicon-c-key';

    protected static ?string $navigationGroup = 'Generated Papers';

    protected static ?int $navigationSort = 2;

    public static function getEloquentQuery(): Builder
    {
        $query = ExamPaper::query();

        if(checkCreateInitiatorPermission()){
            return $query->select('id', 'ref_number', 'program_id', 'year', 'month', 'image','exam_sitting_date', 'question', 'option_a', 'option_b','option_c','option_d','option_e','correct_answer', 'user_id','created_at','updated_at')
                ->groupBy('ref_number')
                ->whereDate('exam_sitting_date',Carbon::now()->subDays(3)->toDateString())
                ->orWhereNotNull('status')
                ->orderBy('updated_at', 'desc');
        }elseif (checkCreateConfirmerPermission()){
            return $query->select('id', 'ref_number', 'program_id', 'year', 'month', 'image','exam_sitting_date', 'question', 'option_a', 'option_b','option_c','option_d','option_e','correct_answer', 'user_id','created_at','updated_at')
                ->groupBy('ref_number')
                ->whereDate('exam_sitting_date',Carbon::now()->subDays(3)->toDateString())
                ->orWhere('status','initiated')
                ->orderBy('updated_at', 'desc');
        }elseif (checkCreateApproverPermission()){
            return $query->select('id', 'ref_number', 'program_id', 'year', 'month', 'image','exam_sitting_date', 'question', 'option_a', 'option_b','option_c','option_d','option_e','correct_answer', 'user_id','created_at','updated_at')
                ->groupBy('ref_number')
                ->whereDate('exam_sitting_date',Carbon::now()->subDays(3)->toDateString())
                ->orWhere('status','confirmed')
                ->orderBy('updated_at', 'desc');
        }

        return $query->select('id', 'ref_number', 'program_id', 'year', 'month', 'image','exam_sitting_date', 'question', 'option_a', 'option_b','option_c','option_d','option_e','correct_answer', 'user_id','created_at','updated_at')
            ->groupBy('ref_number')
            ->whereDate('exam_sitting_date',Carbon::now()->subDays(3)->toDateString())
            ->orderBy('updated_at', 'desc');

    }

    public static function shouldRegisterNavigation(): bool
    {
        //return checkReadExamPaperMarkingKeysPermission();

        return true;
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Placeholder::make('')
                    ->content(function (ExamPaper $record) {
                        $exam_questions = ExamPaper::where('ref_number', $record->ref_number)->get();
                        return view('exam-paper-marking-view', compact('exam_questions'));
                    })
                    ->columnSpanFull()
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('ref_number')
                    ->searchable()->sortable(),
                Tables\Columns\TextColumn::make("program_id")
                    ->label("Program")
                    ->formatStateUsing(function ($record){
                        return Program::where('id', $record->program_id)->first()->name ?? "";
                    }),
                Tables\Columns\TextColumn::make('exam_sitting_date')
                    ->label("Sitting Date/Time")
                    ->dateTime()
                    ->searchable()->sortable(),
                Tables\Columns\TextColumn::make('user_id')
                    ->formatStateUsing(function ($state){
                        return User::where("id", $state)->first()->name ?? "";
                    })
                    ->label("Generated By")
                    ->searchable()->sortable(),
                Tables\Columns\TextColumn::make('status')->sortable()->searchable(),
                Tables\Columns\TextColumn::make('comment')->wrap()->searchable(),
                Tables\Columns\TextColumn::make('updated_at')
                    ->label('Generated At')
                    ->dateTime()
            ])
            ->filters([
                //
            ])
            ->actions([
                ActionGroup::make([
                    Tables\Actions\EditAction::make()->label("View")->visible(function(){
                        return checkCreateApproverPermission() ;
                    }),
                    Tables\Actions\Action::make('confirm')
                        ->requiresConfirmation()
                        ->modalHeading('Confirm Generation')
                        ->modalDescription(function ($record) {
                            return 'You are about to generate a marking key. Confirm to proceed or cancel';
                        })
                        ->modalSubmitActionLabel('Yes, Confirm')
                        ->visible(function(){
                            return checkCreateConfirmerPermission();
                        })
                        ->action(function($record){
                            //update the record
                            $update_key = ExamPaperMarkingKey::where("ref_number", $record->ref_number)->update([
                                "status" => "confirmed"
                            ]);

                            Notification::make()
                                ->success()
                                ->title('Confirmed')
                                ->body('Marking Key Download Confirmed by '.User::where('id', auth()->user()->id)->first()->name);
                        })
                ]),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    //Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListExamPaperMarkingKeys::route('/'),
            //'create' => Pages\CreateExamPaperMarkingKey::route('/create'),
            'edit' => Pages\EditExamPaperMarkingKey::route('/{record}/edit'),
        ];
    }
}
